#version 460 core

#include "common.glsl"

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(rgba16f, binding = 0) writeonly uniform image2DArray imageWrite;

uniform vec2 u_offset;
uniform int u_slot;

void main() {
  const ivec2 texCoord = ivec2(gl_GlobalInvocationID.xy);
  const ivec2 imgSize = imageSize(imageWrite).xy;

  if (texCoord.x >= imgSize.x || texCoord.y >= imgSize.y)
    return;

  vec2 texelSize = 1.f / (imgSize - 1);
  vec2 localUV = texCoord * texelSize;
  vec2 uv = localUV - u_offset;

  vec3 color = vec3(0.f);

  float a = 0.5f;
  float f = 2.0f;
  for (int i = 0; i < 8; i++) {
    color += noised(uv * f) * a;
    a *= 0.95f;
    f *= 2.f;
  }

  imageStore(imageWrite, ivec3(texCoord, u_slot), vec4(color, 1.f));
}

