#version 460 core

#include "common.glsl"

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(rgba16f, binding = 0) readonly  uniform image2D imageRead;
layout(rgba16f, binding = 1) writeonly uniform image2D imageWrite;

layout(std140, binding = 0) uniform ConfigBlock {
  float erosion_scale;
  float erosion_strength;
  float erosion_gully_weight;
  float erosion_detail;

  float ridgeRounding;
  float creaseRounding;

  vec4 erosion_rounding;
  vec4 erosion_onset;
  vec2 erosion_assumed_slope;

  float erosion_cell_scale;
  float erosion_normalization;
  int erosion_octaves;
  float erosion_lacunarity;
  float erosion_gain;

  vec2 terrain_height_offset;

  float height_frequency;
  float height_amp;
  int height_octaves;
  float height_lacunarity;
  float height_gain;

  float heightFunctionScale;
} cfg;

uniform ivec2 u_dirtyX;
uniform ivec2 u_dirtyY;
uniform ivec2 u_pixelDelta;
uniform vec2 u_offset;
uniform float u_heightmapScale;
uniform int u_currOffsetY;

// ----- Pacell Noise Function ---------------------------------------------------------------------------------- //

vec4 PhacelleNoise(vec2 p, vec2 normDir, float freq, float offset, float normalization)  {
  vec2  sideDir = normDir.yx * vec2(-1.f, 1.f) * freq * TAU;
  offset *= TAU;

  // Iterate over 4x4 cells, calculating a stripe pattern for each and blending between them.
  // pInt is the integer part of the current coordinate p, pFrac is the remainder.
  //
  // o   o   o   o
  //
  // o   o   o   o
  //       p
  // o   i   o   o
  //
  // o   o   o   o
  //
  // p: current coordinate    i: integer part of p    o: grid points for 4x4 cells
  //

  vec2 pInt = floor(p);
  vec2 pFrac = fract(p);
  vec2 phaseDir = vec2(0.f);
  float weightSum = 0.f;

  for(int i = -1; i <= 2; i++) {
    for(int j = -1; j <= 2; j++) {
      vec2 gridOffset = vec2(i, j);
      vec2 gridPoint = pInt + gridOffset;
      vec2 randomOffset = hash(gridPoint) * 0.5f;
      vec2 vectorFromCellPoint = pFrac - gridOffset - randomOffset;
      float sqrDist = dot(vectorFromCellPoint, vectorFromCellPoint);
      float weight = exp(-sqrDist * 2.f);

      weight = max(0.f, weight - 0.01111f);
      weightSum += weight;

      float waveInput = dot(vectorFromCellPoint, sideDir) + offset;
      phaseDir += vec2(cos(waveInput), sin(waveInput)) * weight;
    }
  }

  vec2 interpolated = phaseDir / weightSum;
  float magnitude = sqrt(dot(interpolated, interpolated));
  magnitude = max(1.f - normalization, magnitude);

  return vec4(interpolated / magnitude, sideDir);
}

// ----- Erosion ------------------------------------------------------------------------------------------------ //

float pow_inv(float t, float power) {
  // Flip, raise to the specified power, and flip back.
  return 1.0 - pow(1.0 - saturate(t), power);
}

float ease_out(float t) {
  // Flip by subtracting from one.
  float v = 1.0 - saturate(t);
  // Raise to a power of two and flip back.
  return 1.0 - v * v;
}

float smooth_start(float t, float smoothing) {
  if (t >= smoothing)
    return t - 0.5 * smoothing;
  return 0.5 * t * t / smoothing;
}

vec2 safe_normalize(vec2 n) {
  // A div-by-zero-safe replacement for normalize.
  float l = length(n);
  return (abs(l) > 1e-10) ? (n / l) : n;
}

vec4 ErosionFilter(
  // Input parameters that vary per pixel.
  vec2 p, vec3 heightAndSlope, float fadeTarget,
  // Stylistic parameters that may vary per pixel.
  float strength, float gullyWeight, float detail, vec4 rounding, vec4 onset,
  vec2 assumedSlope,
  // Scale related parameters that do not support variation per pixel.
  float scale, int octaves, float lacunarity,
  // Other parameters.
  float gain, float cellScale, float normalization,
  // Output parameters.
  out float ridgeMap, out float debug)
{
  strength *= scale;
  fadeTarget = clamp(fadeTarget, -1.0, 1.0);

  vec3 inputHeightAndSlope = heightAndSlope;
  float freq = 1.0 / (scale * cellScale);
  float slopeLength = max(length(heightAndSlope.yz), 1e-10);
  float magnitude = 0.0;
  float roundingMult = 1.0;

  float roundingForInput = mix(rounding.y, rounding.x, saturate(fadeTarget + 0.5)) * rounding.z;
  float combiMask = ease_out(smooth_start(slopeLength * onset.x, roundingForInput * onset.x));

  float ridgeMapCombiMask = ease_out(slopeLength * onset.z);
  float ridgeMapFadeTarget = fadeTarget;

  vec2 gullySlope = mix(heightAndSlope.yz, heightAndSlope.yz / slopeLength * assumedSlope.x, assumedSlope.y);

  for (int i = 0; i < octaves; i++) {
    vec4 phacelle = PhacelleNoise(p * freq, safe_normalize(gullySlope), cellScale, 0.25, normalization);
    phacelle.zw *= -freq;

    float sloping = abs(phacelle.y);

    gullySlope += sign(phacelle.y) * phacelle.zw * strength * gullyWeight;

    vec3 gullies = vec3(phacelle.x, phacelle.y * phacelle.zw);
    vec3 fadedGullies = mix(vec3(fadeTarget, 0.0, 0.0), gullies * gullyWeight, combiMask);

    heightAndSlope += fadedGullies * strength;
    magnitude += strength;

    fadeTarget = fadedGullies.x;

    float roundingForOctave = mix(rounding.y, rounding.x, saturate(phacelle.x + 0.5)) * roundingMult;
    float newMask = ease_out(smooth_start(sloping * onset.y, roundingForOctave * onset.y));
    combiMask = pow_inv(combiMask, detail) * newMask;

    ridgeMapFadeTarget = mix(ridgeMapFadeTarget, gullies.x, ridgeMapCombiMask);
    float newRidgeMapMask = ease_out(sloping * onset.w);
    ridgeMapCombiMask = ridgeMapCombiMask * newRidgeMapMask;

    strength *= gain;
    freq *= lacunarity;
    roundingMult *= rounding.w;
  }

  ridgeMap = ridgeMapFadeTarget * (1.0 - ridgeMapCombiMask);
  debug = fadeTarget;

  vec3 heightAndSlopeDelta = heightAndSlope - inputHeightAndSlope;

  return vec4(heightAndSlopeDelta, magnitude);
}

// ----- Demonstration ------------------------------------------------------------------------------------------ //

// Used for the height map.
vec3 FractalNoise(vec2 p, float freq, int octaves, float lacunarity, float gain) {
  vec3 n = vec3(0.0);
  float nf = freq;
  float na = 1.0;
  for (int i = 0; i < octaves; i++) {
    n += noised(p * nf) * na * vec3(1.0, nf, nf);
    na *= gain;
    nf *= lacunarity;
  }
  return n;
}

// Used for tree coverage on the height map.
float GetTreesAmount(float height, float normalY, float occlusion, float ridgeMap) {
  return ((
    smoothstep(
      GRASS_HEIGHT + 0.05,
      GRASS_HEIGHT + 0.01,
      height + 0.01 + (occlusion - 0.8) * 0.05
    )
    * smoothstep(
      0.0,
      0.4,
      occlusion
    )
    * smoothstep(0.95, 1.0, normalY)
    * smoothstep(-1.4, 0.0, ridgeMap)
      * smoothstep(
        WATER_HEIGHT + 0.000,
        WATER_HEIGHT + 0.007,
        height
      )
  ) - 0.5) / 0.6;
}

vec4 Heightmap(vec2 p) {
  vec2 pHeight = p / cfg.heightFunctionScale;

  vec3 n = FractalNoise(pHeight, cfg.height_frequency, cfg.height_octaves, cfg.height_lacunarity, cfg.height_gain);
  n *= cfg.height_amp * vec3(cfg.heightFunctionScale, 1.0, 1.0);

  float fadeTarget = clamp(n.x / (cfg.height_amp * 0.6), -1.0, 1.0);

  n = n * 0.5 + vec3(0.5, 0, 0);

  // Store erosion in h (x : height delta, yz : slope delta, w : magnitude).
  // The output ridge map is -1 on creases and 1 on ridges.
  // The output debug value can be set to various values inside the erosion
  float ridgeMap, debug;
  vec4 h = ErosionFilter(
      p, n, fadeTarget, cfg.erosion_strength, cfg.erosion_gully_weight, cfg.erosion_detail,
      cfg.erosion_rounding, cfg.erosion_onset, cfg.erosion_assumed_slope, cfg.erosion_scale,
      cfg.erosion_octaves, cfg.erosion_lacunarity, cfg.erosion_gain, cfg.erosion_cell_scale,
      cfg.erosion_normalization, ridgeMap, debug);

  float offset = mix(cfg.terrain_height_offset.x, -fadeTarget, cfg.terrain_height_offset.y) * h.w;
  float eroded = n.x + h.x + offset;

  float trees = -1.0;
  vec2 deriv = n.yz + h.yz;
  float normalY = 1.0 / sqrt(1.0 + dot(deriv, deriv));
  float treesAmount = GetTreesAmount(eroded, normalY, h.x / h.w + 0.5, ridgeMap);

  trees = (1.0 - pow(noised((p + 0.5) * 200.0).x * 0.5 + 0.5, 2.0) - 1.0 +
           1.0 * treesAmount) * 1.5;

  if (trees > 0.0)
    eroded += trees / 300.0;

  return vec4(
    h.x / h.w * 0.5f + 0.5f,
    ridgeMap  * 0.5f + 0.5f,
    trees     * 0.5f + 0.5f,
    eroded
  );
}

bool isInside(int value, int start, int end) {
  if (start == end)
    return false;

  if (start < end)
    return value >= start && value < end;
  else
    return value >= start || value < end;
}

void main() {
  const ivec2 texCoord = ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y + u_currOffsetY);
  const ivec2 imgSize = imageSize(imageWrite);

  if (texCoord.x >= imgSize.x || texCoord.y >= imgSize.y)
    return;

  bool isDirty = false;
  if (u_pixelDelta.x != 0 && isInside(texCoord.x, u_dirtyX.x, u_dirtyX.y)) isDirty = true;
  if (u_pixelDelta.y != 0 && isInside(texCoord.y, u_dirtyY.x, u_dirtyY.y)) isDirty = true;

  if (!isDirty) {
    vec4 old = imageLoad(imageRead, texCoord);
    imageStore(imageWrite, texCoord, old);
    return;
  }

  vec2 localUV = vec2(texCoord) / (imgSize - 1);
  vec2 uv = (localUV - u_offset) * u_heightmapScale;

  // heightmap (X), normals (YZ) and erosion mask (W)
  vec4 hm = Heightmap(uv);

  imageStore(imageWrite, texCoord, hm);
}

