#version 460 core

#include "common.glsl"

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(rgba16f, binding = 0) readonly  uniform image2D imageRead;
layout(rgba16f, binding = 1) writeonly uniform image2D imageWrite;

uniform ivec2 u_dirtyX;
uniform ivec2 u_dirtyY;
uniform ivec2 u_pixelDelta;
uniform vec2 u_offset;
uniform float u_heightmapScale;
uniform int u_currOffsetY;

bool isInside(int value, int start, int end) {
  if (start == end)
    return false;

  if (start < end)
    return value >= start && value < end;
  else
    return value >= start || value < end;
}

// Noise to add diffuse/normal detail
void main() {
  const ivec2 texCoord = ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y + u_currOffsetY);
  const ivec2 imgSize = imageSize(imageWrite);

  if (texCoord.x >= imgSize.x || texCoord.y >= imgSize.y)
    return;

  bool isDirty = false;
  if (u_pixelDelta.x != 0 && isInside(texCoord.x, u_dirtyX.x, u_dirtyX.y)) isDirty = true;
  if (u_pixelDelta.y != 0 && isInside(texCoord.y, u_dirtyY.x, u_dirtyY.y)) isDirty = true;

  if (!isDirty) {
    vec4 old = imageLoad(imageRead, texCoord);
    imageStore(imageWrite, texCoord, old);
    return;
  }

  vec2 localUV = vec2(texCoord) / (imgSize - 1);
  vec2 uv = (localUV - u_offset) * u_heightmapScale;

  vec3 color = vec3(0.f);

  float a = 0.5f;
  float f = 2.0f;
  for (int i = 0; i < 8; i++) {
    color += noised(uv * f) * a;
    a *= 0.95f;
    f *= 2.f;
  }

  imageStore(imageWrite, texCoord, vec4(color, 1.f));
}

