#version 460 core

#include "common.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

layout(rgba32f, binding = 0) writeonly uniform image2DArray imageWrite;

struct Config {
  float landThresholdA;
  float landThresholdB;
  float continentFreq;
  float initAmplitude;
  float initFrequency;
  float gain;
  float lacunarity;
  float canyonSteps;
  float fbmOffsetFreq0;
  float fbmOffsetFreq1;
  float fbmOffsetFreq2;
  float fbmOffsetTwist;
  float f1VoronoiFreq1;
  float f1VoronoiFreq2;
  float f1f2VoronoiFreq1;
  float f1f2VoronoiFreq2;
  float detailInitAmplitude;
  float detailInitFrequency;
  float detailGain;
  float detailLacunarity;
  int octaves;
  int detailOctaves;
};

uniform vec2 u_nodeCenter;
uniform float u_nodeExtents;
uniform float u_planetRadius;
uniform float u_heightScale;
uniform int u_nodeFaceIdx;
uniform int u_layer;

layout(std140, binding = 0) uniform ConfigBlock {
  Config cfg;
};

vec3 cubeToSphere(vec2 pos, int faceIdx) {
  float u = pos.x;
  float v = pos.y;
  vec3 p;

  switch (faceIdx) {
    case 0: p = vec3( 1,  v,  u); break; // Right
    case 1: p = vec3(-1,  v, -u); break; // Left
    case 2: p = vec3( u,  1,  v); break; // Top
    case 3: p = vec3(-u, -1,  v); break; // Bottom
    case 4: p = vec3(-u,  v,  1); break; // Front
    case 5: p = vec3( u,  v, -1); break; // Back
  }

  return p;
}

float hash(vec3 p) {
  p = fract(p * 0.3183099 + vec3(0.1, 0.1, 0.1));
  p *= dot(p, p + 23.33);

  return fract(p.x * p.y * p.z);
}

float noise(vec3 x) {
  vec3 i = floor(x);
  vec3 f = fract(x);
  f = f * f * (3.0 - 2.0 * f);

  return mix(mix(mix(hash(i + vec3(0,0,0)), hash(i + vec3(1,0,0)), f.x),
                 mix(hash(i + vec3(0,1,0)), hash(i + vec3(1,1,0)), f.x), f.y),
             mix(mix(hash(i + vec3(0,0,1)), hash(i + vec3(1,0,1)), f.x),
                 mix(hash(i + vec3(0,1,1)), hash(i + vec3(1,1,1)), f.x), f.y), f.z);
}

vec2 voronoiF1F2(vec3 p) {
  vec3 baseCell = floor(p);
  vec3 localPos = fract(p);

  float f1 = 8.f;
  float f2 = 8.f;

  for (int z = -1; z <= 1; z++) {
    for (int y = -1; y <= 1; y++) {
      for (int x = -1; x <= 1; x++) {
        vec3 neighbour = vec3(x, y, z);
        vec3 cellSeed = baseCell + neighbour;
        vec3 featurePoint = vec3(hash(cellSeed),
                                 hash(cellSeed + 13.5f),
                                 hash(cellSeed + 27.1f));

        featurePoint = 0.5f + 0.5f * sin(featurePoint * TAU);

        vec3 diff = neighbour + featurePoint - localPos;
        float dist = dot(diff, diff);

        if (dist < f1) {
          f2 = f1;
          f1 = dist;
        } else if (dist < f2) {
          f2 = dist;
        }
      }
    }
  }

  return sqrt(vec2(f1, f2));
}

float fbm(vec3 p, int octaves) {
  float value = 0.f;
  float amplitude = cfg.initAmplitude;
  float frequency = cfg.initFrequency;

  for (int i = 0; i < octaves; i++) {
    value += amplitude * noise(p * frequency);
    frequency *= cfg.lacunarity;
    amplitude *= cfg.gain;
  }

  return value;
}

float evaluateHeight(vec3 sphereDir) {
  // ----- 1. Mountain map ----------------------------------------------------------------- //
  //
  // 2 octabes of F1 Voronoi + FBM displacement
  //

  // Determines where oceans (0.0) and landmasses (1.0) exist
  float continentMap = noise(sphereDir * cfg.continentFreq); // Slow rolling waves
  float landMask = smoothstep(cfg.landThresholdA, cfg.landThresholdB, continentMap); // Sharpen the coastlines

  // The FBM displacement acts as "domain warping" to twist and bend the mountain ranges
  vec3 fbmOffset = vec3(
    fbm(sphereDir * cfg.fbmOffsetFreq0, cfg.octaves),
    fbm(sphereDir * cfg.fbmOffsetFreq1 + vec3(11.5f), cfg.octaves),
    fbm(sphereDir * cfg.fbmOffsetFreq2 + vec3(41.3f), cfg.octaves)
  ) * cfg.fbmOffsetTwist; // Controls how much the mountain ranges twist and curve across continents
  vec3 warpedDir = sphereDir + fbmOffset;

  // The 2 octaves of F1 Voronoi noise
  float macroV1 = voronoiF1F2(warpedDir * cfg.f1VoronoiFreq1).x;
  float macroV2 = voronoiF1F2(warpedDir * cfg.f1VoronoiFreq2).x;

  // Combine octaves (0.7 weight on base, 0.3 on secondary detail)
  float mountainMap = (macroV1 * 0.7f) + (macroV2 * 0.3f);

  // Invert the Voronoi to turn valleys into sharp ridges (Ridge Noise)
  mountainMap = 1.f - mountainMap;
  // Modulate the mountain map by the continent map (leaks slightly past coasts)
  mountainMap *= landMask + 0.15f;

  // ----- 2. Mountain generation noise ------------------------------------------------- //
  //
  // 2 octaves of F2-F1 Voronoi
  // multifractal of 10 octaves of F1 Voronoi
  // 3 octaves of FBM
  //

  // The 2 octaves of F2-F1 Voronoi
  vec2 v1 = voronoiF1F2(warpedDir * cfg.f1f2VoronoiFreq1);
  vec2 v2 = voronoiF1F2(warpedDir * cfg.f1f2VoronoiFreq2);
  float shape1 = v1.y - v1.x;
  float shape2 = v2.y - v2.x;
  float mountainShape = (shape1 * 70.f) * (shape2 * 0.30f);
  mountainShape = pow(max(0.f, mountainShape), 2.f);

  // The multifractal of 10 octaves of F1 Voronoi
  float microErosion = 0.f;
  float amp = cfg.detailInitAmplitude;
  float freq = cfg.detailInitFrequency;
  for (int i = 0; i < cfg.detailOctaves; i++) {
    microErosion += (1.f - voronoiF1F2(sphereDir * freq).x) * amp;
    amp *= cfg.detailGain;
    freq *= cfg.detailLacunarity;
  }

  // The 3 octaves of FBM
  // The Terraced Modifier: Truncates smooth vertical lines into staircase steps (Layers of stone)
  // Floor tricks the float into stepping, creating canyon ledges
  float terraceMask = fbm(sphereDir * 2.f, 3);
  terraceMask = smoothstep(0.45f, 0.65f, terraceMask); // Only isolates certain mountains
  float terracedErosion = floor(microErosion * cfg.canyonSteps) / cfg.canyonSteps;
  // Apply terracing only where the terrace mask allows it
  float processedDetail = mix(microErosion, terracedErosion, terraceMask * 0.65f);

  // ----- 3. Composition --------------------------------------------------------------- //

  float finalMacro = mountainShape * mountainMap;
  float finalDetail = processedDetail * finalMacro;
  float finalHeightFraction = finalMacro + finalDetail;

  // HACK: [finalHeightFraction] supposed to be satureaded
  return finalHeightFraction * u_heightScale;
}

const float eps = 0.001f;

void main() {
  ivec2 texCoord = ivec2(gl_GlobalInvocationID.xy);
  ivec2 size = imageSize(imageWrite).xy;

  if (texCoord.x >= size.x || texCoord.y >= size.y)
    return;

  // [-1, 1]
  vec2 pixelUV = vec2(texCoord) / vec2(size - 1) * 2.f - 1.f;

  vec2 nodeUV = pixelUV * u_nodeExtents + u_nodeCenter;
  vec3 sphereDir = normalize(cubeToSphere(nodeUV, u_nodeFaceIdx));
  float centerHeight = evaluateHeight(sphereDir);

  vec3 sphereDirX = normalize(cubeToSphere(nodeUV + vec2(eps, 0.f), u_nodeFaceIdx));
  vec3 sphereDirY = normalize(cubeToSphere(nodeUV + vec2(0.f, eps), u_nodeFaceIdx));

  float heightX = evaluateHeight(sphereDirX);
  float heightY = evaluateHeight(sphereDirY);

  vec3 posCenter = sphereDir  * (u_planetRadius + centerHeight);
  vec3 posX      = sphereDirX * (u_planetRadius + heightX);
  vec3 posY      = sphereDirY * (u_planetRadius + heightY);

  vec3 normal = normalize(cross(posY - posCenter, posX - posCenter));

  imageStore(imageWrite, ivec3(texCoord, u_layer), vec4(centerHeight, normal));
}

