#version 460 core

#include "../common.glsl"

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

layout(rgba32f, binding = 0) writeonly uniform image2DArray imageWrite;

struct Config {
  float planetRadius;
  float planetRadiusPercent;
  float globalScale;
  float initAmplitude;
  float initFrequency;
  float gain;
  float lacunarity;
  float initAmplitudeDetail;
  float initFrequencyDetail;
  float gainDetail;
  float lacunarityDetail;
  float f1VoronoiFreq;
  float displaceStrength;
  float continentFreq;
  float f2f1VoronoiFreq;
  int octaves;
  int terraceSteps;
};

uniform float u_heightScale;
uniform uint u_offset;

layout(std140, binding = 0) uniform ConfigBlock {
  Config cfg;
};

layout(std140, binding = 1) uniform NodesDataBlock {
  NodeData nodesData[TERRAIN_MAX_NODES];
};

float hash(vec3 p) {
  p = fract(p * 0.3183099 + vec3(0.1, 0.1, 0.1));
  p *= dot(p, p + 23.33);

  return fract(p.x * p.y * p.z);
}

float noise(vec3 x) {
  vec3 i = floor(x);
  vec3 f = fract(x);
  f = f * f * (3.0 - 2.0 * f);

  return mix(mix(mix(hash(i + vec3(0,0,0)), hash(i + vec3(1,0,0)), f.x),
                 mix(hash(i + vec3(0,1,0)), hash(i + vec3(1,1,0)), f.x), f.y),
             mix(mix(hash(i + vec3(0,0,1)), hash(i + vec3(1,0,1)), f.x),
                 mix(hash(i + vec3(0,1,1)), hash(i + vec3(1,1,1)), f.x), f.y), f.z);
}

float voronoiF1(vec3 p) {
  vec3 baseCell = floor(p);
  vec3 localPos = fract(p);

  float f1 = 1.f;

  for (int z = -1; z <= 1; z++) {
    for (int y = -1; y <= 1; y++) {
      for (int x = -1; x <= 1; x++) {
        vec3 neighbour = vec3(x, y, z);
        vec3 cellSeed = baseCell + neighbour;
        vec3 featurePoint = vec3(hash(cellSeed),
                                 hash(cellSeed + 13.5f),
                                 hash(cellSeed + 27.1f));

        featurePoint = 0.5f + 0.5f * sin(featurePoint * TAU);

        vec3 diff = neighbour + featurePoint - localPos;
        float dist = dot(diff, diff);
        f1 = min(f1, dist);
      }
    }
  }

  return sqrt(f1);
}

float voronoiF2F1(vec3 p) {
  vec3 baseCell = floor(p);
  vec3 localPos = fract(p);

  float f1 = 1.f;
  float f2 = 1.f;

  for (int z = -1; z <= 1; z++) {
    for (int y = -1; y <= 1; y++) {
      for (int x = -1; x <= 1; x++) {
        vec3 neighbour = vec3(x, y, z);
        vec3 cellSeed = baseCell + neighbour;
        vec3 featurePoint = vec3(hash(cellSeed),
                                 hash(cellSeed + 13.5f),
                                 hash(cellSeed + 27.1f));

        featurePoint = 0.5f + 0.5f * sin(featurePoint * TAU);

        vec3 diff = neighbour + featurePoint - localPos;
        float dist = dot(diff, diff);

        if (dist < f1) {
          f2 = f1;
          f1 = dist;
        } else if (dist < f2) {
          f2 = dist;
        }
      }
    }
  }

  return sqrt(f2) - sqrt(f1);
}

float fbm(vec3 p, int octaves) {
  float value = 0.f;
  float amplitude = cfg.initAmplitude;
  float frequency = cfg.initFrequency;

  for (int i = 0; i < octaves; i++) {
    value += amplitude * noise(p * frequency);
    frequency *= cfg.lacunarity;
    amplitude *= cfg.gain;
  }

  return value;
}

float evaluateHeight(vec3 sphereDir) {
  sphereDir *= cfg.globalScale;

  // ----- 1. Mountain map ----------------------------------------------------------------- //
  //
  //  2 octaves of F1 Voronoi displaced by FBM and
  //  modulated by the continent map
  //
  // --------------------------------------------------------------------------------------- //

  float mountainMap = 0.f;

  vec3 displace = vec3(
    fbm(sphereDir, cfg.octaves),
    fbm(sphereDir + vec3(11.5f), cfg.octaves),
    fbm(sphereDir + vec3(41.3f), cfg.octaves)
  );

  vec3 sphereDirDisplaced = sphereDir + displace * cfg.displaceStrength;

  mountainMap += 1.f * (1.f - voronoiF1(sphereDirDisplaced));
  mountainMap += 0.5f * (1.f - voronoiF1(sphereDirDisplaced * cfg.f1VoronoiFreq));
  mountainMap /= 1.5f;

  float continentMap = fbm(sphereDir * cfg.continentFreq, 4);
  mountainMap *= smoothstep(0.4f, 0.9f, continentMap);

  // ----- 2. Mountain generation noise ---------------------------------------------------- //
  //
  //  2 octaves of F2-F1 Voronoi
  //  multifractal of 10 octaves of F1 Voronoi
  //  terraced effect modulated by 3 octaves of FBM
  //
  // --------------------------------------------------------------------------------------- //

  float mountainShape = 0.f;

  mountainShape += 1.f * (1.f - voronoiF2F1(sphereDir));
  mountainShape += 0.5f * (1.f - voronoiF2F1(sphereDir * cfg.f2f1VoronoiFreq));
  mountainShape /= 1.5f;

  float detailNoise = 0.f;
  float detailAmplitude = cfg.initAmplitudeDetail;
  float detailFreq = cfg.initFrequencyDetail;
  for (int i = 0; i < 10; i++) {
    float n = 1.f - voronoiF1(sphereDir * detailFreq);
    detailNoise += detailAmplitude * n * mountainShape;
    detailAmplitude *= cfg.gainDetail;
    detailFreq *= cfg.lacunarityDetail;
  }
  float mountainGenerationNoise = mountainShape + detailNoise * 0.3f;

  float scaled = mountainGenerationNoise * cfg.terraceSteps;
  float stepBase = floor(scaled);
  float stepFract = fract(scaled);
  float smoothedFract = smoothstep(0.f, 0.8f, stepFract);
  float terracedNoise = (stepBase + smoothedFract) / cfg.terraceSteps;

  mountainGenerationNoise = clamp01(mountainGenerationNoise);
  mountainGenerationNoise = mix(mountainGenerationNoise, terracedNoise, fbm(sphereDir, 3));

  return mountainMap * mountainGenerationNoise;
}

void main() {
  NodeData node = nodesData[gl_GlobalInvocationID.z + u_offset];
  ivec2 texCoord = ivec2(gl_GlobalInvocationID.xy);
  ivec2 size = imageSize(imageWrite).xy;

  if (texCoord.x >= size.x || texCoord.y >= size.y)
    return;

  // [-1, 1]
  vec2 pixelUV = vec2(texCoord) / vec2(size - 1) * 2.f - 1.f;

  vec2 nodeUV = pixelUV * node.extents + node.center;
  vec3 sphereDir = normalize(cubeToSphere(nodeUV, node.faceIdx));
  float height = evaluateHeight(sphereDir) * u_heightScale;

  vec3 worldPos = sphereDir * (cfg.planetRadius + height);

  imageStore(imageWrite, ivec3(texCoord, node.texLayerIdx), vec4(worldPos, height));
}

