#version 460 core

layout(local_size_x = 16, local_size_y = 16) in;

layout(rgba32f, binding = 0) readonly  uniform image2DArray imgLoad;
layout(rgba32f, binding = 1) writeonly uniform image2DArray imgWrite;

uniform int u_layer;

void main() {
  ivec2 texCoord = ivec2(gl_GlobalInvocationID.xy);
  ivec2 size = imageSize(imgLoad).xy;

  if (texCoord.x >= size.x || texCoord.y >= size.y)
    return;

  vec4 load = imageLoad(imgLoad, ivec3(texCoord, u_layer));

  imageStore(imgWrite, ivec3(texCoord, u_layer), load);
}

